user_role:
  user: 0
  manager: 1
  admin: 2

daily_report_status:
  pending: 0
  read: 1
  commented: 2

ITEMS_PER_PAGE_10: 10
ITEMS_PER_PAGE_5: 5
MIN_LENGTH_DESCRIPTION_10: 10

FILTER_ROLE:
  - user
  - manager

MAX_LENGTH_USERNAME: 50
MAX_LENGTH_EMAIL: 255
MIN_LENGTH_PASSWORD: 6

MIN_LENGTH_TEXT_20: 20

REMEMBER_ME_ENABLED: "1"
TEXT_AREA_ROWS_5: 5

MAILER_HOST: "localhost"
MAILER_PORT: 3000

RANDOM_PW_LENGTH: 6

active_status:
  - active
  - inactive

ROLE_MANAGER: "manager"

AVATAR_SIZE_200: 200
IMAGE_SIZE_LARGE_LIMIT_5: 5
IMAGE_RESIZE_TO_LIMIT_500_500: [500, 500]
